# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: startit_api_development
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: startit_api_test
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  port: 5432


production:
  <<: *default
  database: startit_api_production
  username: <%= ENV['STARTIT_API_PRODUCTION_POSTGRES_USERNAME'] %>
  password: <%= ENV['STARTIT_API_PRODUCTION_POSTGRES_PASSWORD'] %>
